spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  datasource:
    url: jdbc:mysql://hrmis-aiven-instance-hrmis.h.aivencloud.com:24695/staff_db?ssl-mode=REQUIRED
    username: avnadmin
    password: AVNS_CVMazlms80CpHegeIha
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  config:
    import: "optional:${SPRING_CONFIG_IMPORT}"

---

spring:
  config:
    activate:
      on-profile: dev
    import: "optional:configserver:http://localhost:8067/"
  application:
    name: staff-service
  datasource:
    url: jdbc:mysql://localhost:3306/staff_db
    username: root
    password: venura2501
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8086

eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka/"
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

---

spring:
  config:
    activate:
      on-profile: dev-dis-eureka
    import: "optional:configserver:http://localhost:8067/"
  application:
    name: staff-service
  datasource:
    url: jdbc:mysql://localhost:3306/staff_db
    username: root
    password: venura2501
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8086

eureka:
  client:
    enabled: false
---