steps:

# ----------------------------------------------------------------------------------------------------------------------------------------------------------------

- name: 'gcr.io/cloud-builders/mvn'
  dir: 'config-server'
  args: ['package', '-DskipTests']
  id: 'Package Config Server'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/stone-album-437618-f8/hrmis-artifact-registry/config-server', './config-server' ]
  id: 'Build Config Server Docker Image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/stone-album-437618-f8/hrmis-artifact-registry/config-server' ]
  id: 'Push Config Server Docker Image'
  
# ----------------------------------------------------------------------------------------------------------------------------------------------------------------

- name: 'gcr.io/cloud-builders/mvn'
  dir: 'eureka-server'
  args: ['package', '-DskipTests']
  id: 'Package Eureka Server'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/stone-album-437618-f8/hrmis-artifact-registry/eureka-server', './eureka-server' ]
  id: 'Build Eureka Server Docker Image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/stone-album-437618-f8/hrmis-artifact-registry/eureka-server' ]
  id: 'Push Eureka Server Docker Image'
  
# ----------------------------------------------------------------------------------------------------------------------------------------------------------------

- name: 'gcr.io/cloud-builders/mvn'
  dir: 'booking-service'
  args: ['package', '-DskipTests']
  id: 'Package Booking Service'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/stone-album-437618-f8/hrmis-artifact-registry/booking-service', './booking-service' ]
  id: 'Build Booking Service Docker Image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/stone-album-437618-f8/hrmis-artifact-registry/booking-service' ]
  id: 'Push Booking Service Docker Image'
  
# ----------------------------------------------------------------------------------------------------------------------------------------------------------------

- name: 'gcr.io/cloud-builders/mvn'
  dir: 'menu-service'
  args: ['package', '-DskipTests']
  id: 'Package Menu Service'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/stone-album-437618-f8/hrmis-artifact-registry/menu-service', './menu-service' ]
  id: 'Build Menu Service Docker Image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/stone-album-437618-f8/hrmis-artifact-registry/menu-service' ]
  id: 'Push Menu Service Docker Image'
  
# ----------------------------------------------------------------------------------------------------------------------------------------------------------------

- name: 'gcr.io/cloud-builders/mvn'
  dir: 'order-service'
  args: ['package', '-DskipTests']
  id: 'Package Order Service'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/stone-album-437618-f8/hrmis-artifact-registry/order-service', './order-service' ]
  id: 'Build Order Service Docker Image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/stone-album-437618-f8/hrmis-artifact-registry/order-service' ]
  id: 'Push Order Service Docker Image'
  
# ----------------------------------------------------------------------------------------------------------------------------------------------------------------

- name: 'gcr.io/cloud-builders/mvn'
  dir: 'review-service'
  args: ['package', '-DskipTests']
  id: 'Package Review Service'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/stone-album-437618-f8/hrmis-artifact-registry/review-service', './review-service' ]
  id: 'Build Review Service Docker Image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/stone-album-437618-f8/hrmis-artifact-registry/review-service' ]
  id: 'Push Review Service Docker Image'
  
# ----------------------------------------------------------------------------------------------------------------------------------------------------------------

- name: 'gcr.io/cloud-builders/mvn'
  dir: 'staff-service'
  args: ['package', '-DskipTests']
  id: 'Package Staff Service'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/stone-album-437618-f8/hrmis-artifact-registry/staff-service', './staff-service' ]
  id: 'Build Staff Service Docker Image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/stone-album-437618-f8/hrmis-artifact-registry/staff-service' ]
  id: 'Push Staff Service Docker Image'
  
# ----------------------------------------------------------------------------------------------------------------------------------------------------------------

- name: 'gcr.io/cloud-builders/mvn'
  dir: 'table-reservation-service'
  args: ['package', '-DskipTests']
  id: 'Package Table Reservation Service'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/stone-album-437618-f8/hrmis-artifact-registry/table-reservation-service', './table-reservation-service' ]
  id: 'Build Table Reservation Service Docker Image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/stone-album-437618-f8/hrmis-artifact-registry/table-reservation-service' ]
  id: 'Push Table Reservation Service Docker Image'
  
# ----------------------------------------------------------------------------------------------------------------------------------------------------------------

- name: 'gcr.io/cloud-builders/mvn'
  dir: 'auth-service'
  args: ['package', '-DskipTests']
  id: 'Package Auth Service'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/stone-album-437618-f8/hrmis-artifact-registry/auth-service', './auth-service' ]
  id: 'Build API Gateway Docker Image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/stone-album-437618-f8/hrmis-artifact-registry/auth-service' ]
  id: 'Push Auth Service Docker Image'
  
# ----------------------------------------------------------------------------------------------------------------------------------------------------------------

- name: 'gcr.io/cloud-builders/mvn'
  dir: 'api-gateway'
  args: ['package', '-DskipTests']
  id: 'Package API Gateway'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/stone-album-437618-f8/hrmis-artifact-registry/api-gateway', './api-gateway' ]
  id: 'Build API Gateway Docker Image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/stone-album-437618-f8/hrmis-artifact-registry/api-gateway' ]
  id: 'Push API Gateway Docker Image'
  
# ----------------------------------------------------------------------------------------------------------------------------------------------------------------

- name: 'google/cloud-sdk:latest'
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    gcloud deploy apply --file deploy/pipeline.yaml --region=us-central1
    gcloud deploy apply --file deploy/dev.yaml --region=us-central1
    gcloud deploy releases create 'app-release-${SHORT_SHA}' --delivery-pipeline=gke-cicd-pipeline --region=us-central1 --skaffold-file=skaffold.yaml


options:
  logging: CLOUD_LOGGING_ONLY