apiVersion: skaffold/v4beta9
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  local: {}
manifests:
  rawYaml:
    - https://github.com/rabbitmq/cluster-operator/releases/latest/download/cluster-operator.yml
    - ./k8s/*
  
deploy:
  kubectl: {}
  logs:
    prefix: container