apiVersion: skaffold/v4beta11
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  local: {}
manifests:
  rawYaml:
    - ./k8s/*
  
deploy:
  kubectl:
    hooks:
      before:
        - host:
            command: ["kubectl", "apply", "-f", "https://github.com/rabbitmq/cluster-operator/releases/latest/download/cluster-operator.yml"]
  logs:
    prefix: container