spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  cloud:
    gateway:
      routes:
        - id: REVIEW-SERVICE
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/api/review/**
          filters:
            - RewritePath=/api/review/(?<segment>.*), /review/${segment}

        - id: MENU-SERVICE
          uri: lb://MENU-SERVICE
          predicates:
            - Path=/api/menu/**
          filters:
            - RewritePath=/api/menu/(?<segment>.*), /menu/${segment}

        - id: BOOKING-SERVICE
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/booking/**, /api/room-type/**, /api/room/**
          filters:
            - RewritePath=/api/booking/(?<segment>.*), /booking/${segment}
            - RewritePath=/api/room-type/(?<segment>.*), /room-type/${segment}
            - RewritePath=/api/room/(?<segment>.*), /room/${segment}
  config:
    import: "optional:${SPRING_CONFIG_IMPORT}"

---

spring:
  config:
    activate:
      on-profile: dev
    import: "optional:configserver:http://localhost:8067/"
  application:
    name: api-gateway

server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka/"
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5


---