apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: production-rabbitmqcluster
spec:
  replicas: 1
  rabbitmq:
    additionalConfig: |
      log.console.level = info
      channel_max = 200
      default_user= guest 
      default_pass = guest
      default_user_tags.administrator = true
  resources:
    requests:
      cpu: 400m        
      memory: 1Gi    
    limits:
      cpu: 600m      
      memory: 1.5Gi  
  service:
    type: LoadBalancer
