apiVersion: v1
kind: Service
metadata:
  name: eureka
  labels:
    app: eureka
spec:
  clusterIP: None
  ports:
    - port: 8761
      name: eureka
  selector:
    app: eureka

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
spec:
  serviceName: "eureka"
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: us-central1-docker.pkg.dev/sound-bee-428509-q1/hrmis-artifact-registry/eureka-server
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
          env:
          - name: SPRING_APPLICATION_NAME
            valueFrom:
              configMapKeyRef:
                name: hrmis-config-map
                key: EUREKA_APPLICATION_NAME
          - name: HOSTNAME
            valueFrom:
              configMapKeyRef:
                name: hrmis-config-map
                key: EUREKA_HOSTNAME
          - name: SPRING_CONFIG_IMPORT
            valueFrom: 
              configMapKeyRef:
                name: hrmis-config-map
                key: SPRING_CONFIG_IMPORT
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            valueFrom: 
              configMapKeyRef:
                name: hrmis-config-map
                key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE

---                  

apiVersion: v1
kind: Service
metadata:
  name: eureka-lb
  labels:
    app: eureka
spec:
  selector:
    app: eureka
  type: NodePort
  ports:
    - port: 80
      targetPort: 8761
