apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu-service-deployment
  labels:
    app: menu-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: menu-service
  template:
    metadata:
      labels:
        app: menu-service
    spec:
      containers:
      - name: menu-service
        image: us-central1-docker.pkg.dev/stone-album-437618-f8/hrmis-artifact-registry/menu-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8084
        env:
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              name: hrmis-config-map
              key: MENU_SERVICE_APPLICATION_NAME
        - name: SPRING_CONFIG_IMPORT
          valueFrom: 
            configMapKeyRef:
              name: hrmis-config-map
              key: SPRING_CONFIG_IMPORT
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom: 
            configMapKeyRef:
              name: hrmis-config-map
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom: 
            secretKeyRef:
              name: database-creds
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: database-creds
              key: password
        - name: SPRING_DATASOURCE_URL
          valueFrom: 
            configMapKeyRef:
              name: hrmis-config-map
              key: MENU_SERVICE_DATASOURCE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: menu-service
spec:
  selector:
    app: menu-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8084