apiVersion: apps/v1
kind: Deployment
metadata:
  name: staff-service-deployment
  labels:
    app: staff-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: staff-service
  template:
    metadata:
      labels:
        app: staff-service
    spec:
      containers:
      - name: staff-service
        image: venuraks/sep-16-staff-service:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8086
        env:
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              name: hrmis-config-map
              key: STAFF_SERVICE_APPLICATION_NAME
        - name: SPRING_CONFIG_IMPORT
          valueFrom: 
            configMapKeyRef:
              name: hrmis-config-map
              key: SPRING_CONFIG_IMPORT
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom: 
            configMapKeyRef:
              name: hrmis-config-map
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
apiVersion: v1
kind: Service
metadata:
  name: staff-service
spec:
  selector:
    app: staff-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8086