apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations: {}
  labels: {}
description: dev
gke:
  cluster: projects/sound-bee-428509-q1/locations/us-central1-c/clusters/hrmis-cluster-1