server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/SEP-G16/sep-backend-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
          username: ${GIT_USERNAME}
          password: ${GIT_ACCESS_TOKEN}
