spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  config:
    import: "optional:${SPRING_CONFIG_IMPORT}"
---

spring:
  config:
    activate:
      on-profile: dev
    import: "optional:configserver:http://localhost:8067/"
  application:
    name: email-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: "teamceylonresort@gmail.com"
    password: "nksz tyxs gcbo nbjq"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8079

eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka/"
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

---

spring:
  config:
    activate:
      on-profile: dev-dis-eureka
    import: "optional:configserver:http://localhost:8067/"
  application:
    name: email-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: "teamceylonresort@gmail.com"
    password: "nksz tyxs gcbo nbjq"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8079

eureka:
  client:
    enabled: false
---
